#!/usr/bin/env python
import subprocess
import sys
import os
import re

import iarchive
if (os.path.exists(sys.argv[1])):
   exit
else:
   base=os.path.basename(sys.argv[1])
   base=re.sub('\.html$', '', base)
   print base
   if "nowrap" in sys.argv:
      args=["/src/epub/abbyy2html",base,"nowrap"]
   else:
      args=["/src/epub/abbyy2html",base]
   proc=subprocess.Popen(args,stdout=open(sys.argv[1],"w"))
   proc.wait()
