iso639_2_T = {
    "aar": "aa", 
    "abk": "ab", 
    "afr": "af", 
    "aka": "ak", 
    "amh": "am", 
    "ara": "ar", 
    "arg": "an", 
    "asm": "as", 
    "ava": "av", 
    "ave": "ae", 
    "aym": "ay", 
    "aze": "az", 
    "bak": "ba", 
    "bam": "bm", 
    "bel": "be", 
    "ben": "bn", 
    "bih": "bh", 
    "bis": "bi", 
    "bod": "bo", 
    "bos": "bs", 
    "bre": "br", 
    "bul": "bg", 
    "cat": "ca", 
    "ces": "cs", 
    "cha": "ch", 
    "che": "ce", 
    "chu": "cu", 
    "chv": "cv", 
    "cor": "kw", 
    "cos": "co", 
    "cre": "cr", 
    "cym": "cy", 
    "dan": "da", 
    "deu": "de", 
    "div": "dv", 
    "dzo": "dz", 
    "ell": "el", 
    "eng": "en", 
    "epo": "eo", 
    "est": "et", 
    "eus": "eu", 
    "ewe": "ee", 
    "fao": "fo", 
    "fas": "fa", 
    "fij": "fj", 
    "fin": "fi", 
    "fra": "fr", 
    "fry": "fy", 
    "ful": "ff", 
    "gla": "gd", 
    "gle": "ga", 
    "glg": "gl", 
    "glv": "gv", 
    "grn": "gn", 
    "guj": "gu", 
    "hat": "ht", 
    "hau": "ha", 
    "heb": "he", 
    "her": "hz", 
    "hin": "hi", 
    "hmo": "ho", 
    "hrv": "hr", 
    "hun": "hu", 
    "hye": "hy", 
    "ibo": "ig", 
    "ido": "io", 
    "iii": "ii", 
    "iku": "iu", 
    "ile": "ie", 
    "ina": "ia", 
    "ind": "id", 
    "ipk": "ik", 
    "isl": "is", 
    "ita": "it", 
    "jav": "jv", 
    "jpn": "ja", 
    "kal": "kl", 
    "kan": "kn", 
    "kas": "ks", 
    "kat": "ka", 
    "kau": "kr", 
    "kaz": "kk", 
    "khm": "km", 
    "kik": "ki", 
    "kin": "rw", 
    "kir": "ky", 
    "kom": "kv", 
    "kon": "kg", 
    "kor": "ko", 
    "kua": "kj", 
    "kur": "ku", 
    "lao": "lo", 
    "lat": "la", 
    "lav": "lv", 
    "lim": "li", 
    "lin": "ln", 
    "lit": "lt", 
    "ltz": "lb", 
    "lub": "lu", 
    "lug": "lg", 
    "mah": "mh", 
    "mal": "ml", 
    "mar": "mr", 
    "mkd": "mk", 
    "mlg": "mg", 
    "mlt": "mt", 
    "mon": "mn", 
    "mri": "mi", 
    "msa": "ms", 
    "mya": "my", 
    "nau": "na", 
    "nav": "nv", 
    "nbl": "nr", 
    "nde": "nd", 
    "ndo": "ng", 
    "nep": "ne", 
    "nld": "nl", 
    "nno": "nn", 
    "nob": "nb", 
    "nor": "no", 
    "nya": "ny", 
    "oci": "oc", 
    "oji": "oj", 
    "ori": "or", 
    "orm": "om", 
    "oss": "os", 
    "pan": "pa", 
    "pli": "pi", 
    "pol": "pl", 
    "por": "pt", 
    "pus": "ps", 
    "que": "qu", 
    "roh": "rm", 
    "ron": "ro", 
    "run": "rn", 
    "rus": "ru", 
    "sag": "sg", 
    "san": "sa", 
    "sin": "si", 
    "slk": "sk", 
    "slv": "sl", 
    "sme": "se", 
    "smo": "sm", 
    "sna": "sn", 
    "snd": "sd", 
    "som": "so", 
    "sot": "st", 
    "spa": "es", 
    "sqi": "sq", 
    "srd": "sc", 
    "srp": "sr", 
    "ssw": "ss", 
    "sun": "su", 
    "swa": "sw", 
    "swe": "sv", 
    "tah": "ty", 
    "tam": "ta", 
    "tat": "tt", 
    "tel": "te", 
    "tgk": "tg", 
    "tgl": "tl", 
    "tha": "th", 
    "tir": "ti", 
    "ton": "to", 
    "tsn": "tn", 
    "tso": "ts", 
    "tuk": "tk", 
    "tur": "tr", 
    "twi": "tw", 
    "uig": "ug", 
    "ukr": "uk", 
    "urd": "ur", 
    "uzb": "uz", 
    "ven": "ve", 
    "vie": "vi", 
    "vol": "vo", 
    "wln": "wa", 
    "wol": "wo", 
    "xho": "xh", 
    "yid": "yi", 
    "yor": "yo", 
    "zha": "za", 
    "zho": "zh", 
    "zul": "zu"
}
iso639_2_B = {
    "alb": "sq", 
    "arm": "hy", 
    "baq": "eu", 
    "bur": "my", 
    "chi": "zh", 
    "cze": "cs", 
    "dut": "nl", 
    "fre": "fr", 
    "geo": "ka", 
    "ger": "de", 
    "gre": "el", 
    "ice": "is", 
    "mac": "mk", 
    "mao": "mi", 
    "may": "ms", 
    "per": "fa", 
    "rum": "ro", 
    "slo": "sk", 
    "tib": "bo", 
    "wel": "cy"
}
iso639_3 = {
    "aar": "aa", 
    "abk": "ab", 
    "afr": "af", 
    "aka": "ak", 
    "amh": "am", 
    "ara": "ar", 
    "arg": "an", 
    "asm": "as", 
    "ava": "av", 
    "ave": "ae", 
    "aym": "ay", 
    "aze": "az", 
    "bak": "ba", 
    "bam": "bm", 
    "bel": "be", 
    "ben": "bn", 
    "bis": "bi", 
    "bod": "bo", 
    "bos": "bs", 
    "bre": "br", 
    "bul": "bg", 
    "cat": "ca", 
    "ces": "cs", 
    "cha": "ch", 
    "che": "ce", 
    "chu": "cu", 
    "chv": "cv", 
    "cor": "kw", 
    "cos": "co", 
    "cre": "cr", 
    "cym": "cy", 
    "dan": "da", 
    "deu": "de", 
    "div": "dv", 
    "dzo": "dz", 
    "ell": "el", 
    "eng": "en", 
    "epo": "eo", 
    "est": "et", 
    "eus": "eu", 
    "ewe": "ee", 
    "fao": "fo", 
    "fas": "fa", 
    "fij": "fj", 
    "fin": "fi", 
    "fra": "fr", 
    "fry": "fy", 
    "ful": "ff", 
    "gla": "gd", 
    "gle": "ga", 
    "glg": "gl", 
    "glv": "gv", 
    "grn": "gn", 
    "guj": "gu", 
    "hat": "ht", 
    "hau": "ha", 
    "heb": "he", 
    "her": "hz", 
    "hin": "hi", 
    "hmo": "ho", 
    "hrv": "hr", 
    "hun": "hu", 
    "hye": "hy", 
    "ibo": "ig", 
    "ido": "io", 
    "iii": "ii", 
    "iku": "iu", 
    "ile": "ie", 
    "ina": "ia", 
    "ind": "id", 
    "ipk": "ik", 
    "isl": "is", 
    "ita": "it", 
    "jav": "jv", 
    "jpn": "ja", 
    "kal": "kl", 
    "kan": "kn", 
    "kas": "ks", 
    "kat": "ka", 
    "kau": "kr", 
    "kaz": "kk", 
    "khm": "km", 
    "kik": "ki", 
    "kin": "rw", 
    "kir": "ky", 
    "kom": "kv", 
    "kon": "kg", 
    "kor": "ko", 
    "kua": "kj", 
    "kur": "ku", 
    "lao": "lo", 
    "lat": "la", 
    "lav": "lv", 
    "lim": "li", 
    "lin": "ln", 
    "lit": "lt", 
    "ltz": "lb", 
    "lub": "lu", 
    "lug": "lg", 
    "mah": "mh", 
    "mal": "ml", 
    "mar": "mr", 
    "mkd": "mk", 
    "mlg": "mg", 
    "mlt": "mt", 
    "mon": "mn", 
    "mri": "mi", 
    "msa": "ms", 
    "mya": "my", 
    "nau": "na", 
    "nav": "nv", 
    "nbl": "nr", 
    "nde": "nd", 
    "ndo": "ng", 
    "nep": "ne", 
    "nld": "nl", 
    "nno": "nn", 
    "nob": "nb", 
    "nor": "no", 
    "nya": "ny", 
    "oci": "oc", 
    "oji": "oj", 
    "ori": "or", 
    "orm": "om", 
    "oss": "os", 
    "pan": "pa", 
    "pli": "pi", 
    "pol": "pl", 
    "por": "pt", 
    "pus": "ps", 
    "que": "qu", 
    "roh": "rm", 
    "ron": "ro", 
    "run": "rn", 
    "rus": "ru", 
    "sag": "sg", 
    "san": "sa", 
    "sin": "si", 
    "slk": "sk", 
    "slv": "sl", 
    "sme": "se", 
    "smo": "sm", 
    "sna": "sn", 
    "snd": "sd", 
    "som": "so", 
    "sot": "st", 
    "spa": "es", 
    "sqi": "sq", 
    "srd": "sc", 
    "srp": "sr", 
    "ssw": "ss", 
    "sun": "su", 
    "swa": "sw", 
    "swe": "sv", 
    "tah": "ty", 
    "tam": "ta", 
    "tat": "tt", 
    "tel": "te", 
    "tgk": "tg", 
    "tgl": "tl", 
    "tha": "th", 
    "tir": "ti", 
    "ton": "to", 
    "tsn": "tn", 
    "tso": "ts", 
    "tuk": "tk", 
    "tur": "tr", 
    "twi": "tw", 
    "uig": "ug", 
    "ukr": "uk", 
    "urd": "ur", 
    "uzb": "uz", 
    "ven": "ve", 
    "vie": "vi", 
    "vol": "vo", 
    "wln": "wa", 
    "wol": "wo", 
    "xho": "xh", 
    "yid": "yi", 
    "yor": "yo", 
    "zha": "za", 
    "zho": "zh", 
    "zul": "zu"
}
lang_name = {
    "Abkhazian": "ab", 
    "Afar": "aa", 
    "Afrikaans": "af", 
    "Akan": "ak", 
    "Albanian": "sq", 
    "Amharic": "am", 
    "Arabic": "ar", 
    "Aragonese": "an", 
    "Armenian": "hy", 
    "Assamese": "as", 
    "Avaric": "av", 
    "Avestan": "ae", 
    "Aymara": "ay", 
    "Azerbaijani": "az", 
    "Bambara": "bm", 
    "Bashkir": "ba", 
    "Basque": "eu", 
    "Belarusian": "be", 
    "Bengali": "bn", 
    "Bihari": "bh", 
    "Bislama": "bi", 
    "Bosnian": "bs", 
    "Breton": "br", 
    "Bulgarian": "bg", 
    "Burmese": "my", 
    "Castilian": "es", 
    "Catalan": "ca", 
    "Central Khmer": "km", 
    "Chamorro": "ch", 
    "Chechen": "ce", 
    "Chewa": "ny", 
    "Chichewa": "ny", 
    "Chinese": "zh", 
    "Chuang": "za", 
    "Church Slavic": "cu", 
    "Church Slavonic": "cu", 
    "Chuvash": "cv", 
    "Cornish": "kw", 
    "Corsican": "co", 
    "Cree": "cr", 
    "Croatian": "hr", 
    "Czech": "cs", 
    "Danish": "da", 
    "Dhivehi": "dv", 
    "Divehi": "dv", 
    "Dutch": "nl", 
    "Dzongkha": "dz", 
    "English": "en", 
    "Esperanto": "eo", 
    "Estonian": "et", 
    "Ewe": "ee", 
    "Faroese": "fo", 
    "Fijian": "fj", 
    "Finnish": "fi", 
    "Flemish": "nl", 
    "French": "fr", 
    "Fulah": "ff", 
    "Gaelic": "gd", 
    "Galician": "gl", 
    "Ganda": "lg", 
    "Georgian": "ka", 
    "German": "de", 
    "Gikuyu": "ki", 
    "Greenlandic": "kl", 
    "Guaran\u00ed": "gn", 
    "Gujarati": "gu", 
    "Haitian": "ht", 
    "Haitian Creole": "ht", 
    "Hausa": "ha", 
    "Herero": "hz", 
    "Hindi": "hi", 
    "Hiri Motu": "ho", 
    "Hungarian": "hu", 
    "Icelandic": "is", 
    "Ido": "io", 
    "Igbo": "ig", 
    "Indonesian": "id", 
    "Interlingua (International Auxiliary Language Association)": "ia", 
    "Interlingue": "ie", 
    "Inuktitut": "iu", 
    "Inupiaq": "ik", 
    "Irish": "ga", 
    "Italian": "it", 
    "Japanese": "ja", 
    "Javanese": "jv", 
    "Kalaallisut": "kl", 
    "Kannada": "kn", 
    "Kanuri": "kr", 
    "Kashmiri": "ks", 
    "Kazakh": "kk", 
    "Kikuyu": "ki", 
    "Kinyarwanda": "rw", 
    "Kirghiz": "ky", 
    "Komi": "kv", 
    "Kongo": "kg", 
    "Korean": "ko", 
    "Kuanyama": "kj", 
    "Kurdish": "ku", 
    "Kwanyama": "kj", 
    "Kyrgyz": "ky", 
    "Lao": "lo", 
    "Latin": "la", 
    "Latvian": "lv", 
    "Letzeburgesch": "lb", 
    "Limburgan": "li", 
    "Limburger": "li", 
    "Limburgish": "li", 
    "Lingala": "ln", 
    "Lithuanian": "lt", 
    "Luba-Katanga": "lu", 
    "Luxembourgish": "lb", 
    "Macedonian": "mk", 
    "Malagasy": "mg", 
    "Malay": "ms", 
    "Malayalam": "ml", 
    "Maldivian": "dv", 
    "Maltese": "mt", 
    "Manx": "gv", 
    "Marathi": "mr", 
    "Marshallese": "mh", 
    "Modern Greek": "el", 
    "Modern Hebrew": "he", 
    "Moldavian": "ro", 
    "Moldovan": "ro", 
    "Mongolian": "mn", 
    "M\u0101ori": "mi", 
    "Nauru": "na", 
    "Navaho": "nv", 
    "Navajo": "nv", 
    "Ndonga": "ng", 
    "Nepali": "ne", 
    "North Ndebele": "nd", 
    "Northern Sami": "se", 
    "Norwegian": "no", 
    "Norwegian Bokm\u00e5l": "nb", 
    "Norwegian Nynorsk": "nn", 
    "Nuosu": "ii", 
    "Nyanja": "ny", 
    "Occidental": "ie", 
    "Occitan (after 1500)": "oc", 
    "Ojibwa": "oj", 
    "Old Bulgarian": "cu", 
    "Old Church Slavonic": "cu", 
    "Old Slavonic": "cu", 
    "Oriya": "or", 
    "Oromo": "om", 
    "Ossetian": "os", 
    "Ossetic": "os", 
    "Panjabi": "pa", 
    "Pashto": "ps", 
    "Persian": "fa", 
    "Polish": "pl", 
    "Portuguese": "pt", 
    "Punjabi": "pa", 
    "Pushto": "ps", 
    "P\u0101li": "pi", 
    "Quechua": "qu", 
    "Romanian": "ro", 
    "Romansh": "rm", 
    "Rundi": "rn", 
    "Russian": "ru", 
    "Samoan": "sm", 
    "Sango": "sg", 
    "Sanskrit": "sa", 
    "Sardinian": "sc", 
    "Scottish Gaelic": "gd", 
    "Serbian": "sr", 
    "Shona": "sn", 
    "Sichuan Yi": "ii", 
    "Sindhi": "sd", 
    "Sinhala": "si", 
    "Sinhalese": "si", 
    "Slovak": "sk", 
    "Slovene": "sl", 
    "Somali": "so", 
    "South Ndebele": "nr", 
    "Southern Sotho": "st", 
    "Spanish": "es", 
    "Sundanese": "su", 
    "Swahili": "sw", 
    "Swati": "ss", 
    "Swedish": "sv", 
    "Tagalog": "tl", 
    "Tahitian": "ty", 
    "Tajik": "tg", 
    "Tamil": "ta", 
    "Tatar": "tt", 
    "Telugu": "te", 
    "Thai": "th", 
    "Tibetan": "bo", 
    "Tigrinya": "ti", 
    "Tonga (Tonga Islands)": "to", 
    "Tsonga": "ts", 
    "Tswana": "tn", 
    "Turkish": "tr", 
    "Turkmen": "tk", 
    "Twi": "tw", 
    "Uighur": "ug", 
    "Ukrainian": "uk", 
    "Urdu": "ur", 
    "Uyghur": "ug", 
    "Uzbek": "uz", 
    "Valencian": "ca", 
    "Venda": "ve", 
    "Vietnamese": "vi", 
    "Volap\u00fck": "vo", 
    "Walloon": "wa", 
    "Welsh": "cy", 
    "Western Frisian": "fy", 
    "Wolof": "wo", 
    "Xhosa": "xh", 
    "Yiddish": "yi", 
    "Yoruba": "yo", 
    "Zhuang": "za", 
    "Zulu": "zu"
}
native_name = {
    "Afaan Oromoo": "om", 
    "Afaraf": "aa", 
    "Afrikaans": "af", 
    "Akan": "ak", 
    "Aragon\u00e9s": "an", 
    "Ava\u00f1e'\u1ebd": "gn", 
    "Bahasa Indonesia": "id", 
    "Basa Sunda": "su", 
    "Bislama": "bi", 
    "Catal\u00e0": "ca", 
    "Chamoru": "ch", 
    "Cymraeg": "cy", 
    "Davvis\u00e1megiella": "se", 
    "Deutsch": "de", 
    "Din\u00e9 bizaad": "nv", 
    "Din\u00e9k\u02bceh\u01f0\u00ed": "nv", 
    "Ekakair\u0169 Naoero": "na", 
    "English": "en", 
    "Esperanto": "eo", 
    "E\u028begbe": "ee", 
    "Frysk": "fy", 
    "Fulfulde": "ff", 
    "Gaeilge": "ga", 
    "Gaelg": "gv", 
    "Gailck": "gv", 
    "Galego": "gl", 
    "G\u00e0idhlig": "gd", 
    "G\u0129k\u0169y\u0169": "ki", 
    "Hausa": "ha", 
    "Hiri Motu": "ho", 
    "Ido": "io", 
    "Igbo": "ig", 
    "Ikinyarwanda": "rw", 
    "Interlingua": "ia", 
    "Interlingue": "ie", 
    "Italiano": "it", 
    "I\u00f1upiaq": "ik", 
    "I\u00f1upiatun": "ik", 
    "Kajin M\u0327aje\u013c": "mh", 
    "Kanuri": "kr", 
    "Kernewek": "kw", 
    "KiKongo": "kg", 
    "Kichwa": "qu", 
    "Kiswahili": "sw", 
    "Krey\u00f2l ayisyen": "ht", 
    "Kuanyama": "kj", 
    "Limburgs": "li", 
    "Ling\u00e1la": "ln", 
    "Luganda": "lg", 
    "L\u00ebtzebuergesch": "lb", 
    "Magyar": "hu", 
    "Malagasy fiteny": "mg", 
    "Malti": "mt", 
    "Nederlands": "nl", 
    "Norsk": "no", 
    "Norsk bokm\u00e5l": "nb", 
    "Norsk nynorsk": "nn", 
    "Occitan": "oc", 
    "Otjiherero": "hz", 
    "Owambo": "ng", 
    "Portugu\u00eas": "pt", 
    "Pulaar": "ff", 
    "Pular": "ff", 
    "Reo M\u0101`ohi": "ty", 
    "Runa Simi": "qu", 
    "Saw cuengh": "za", 
    "Sa\u026f cue\u014b\u0185": "za", 
    "Sesotho": "st", 
    "Setswana": "tn", 
    "Shqip": "sq", 
    "SiSwati": "ss", 
    "Soomaaliga": "so", 
    "Ti\u1ebfng Vi\u1ec7t": "vi", 
    "Tshiven\u1e13a": "ve", 
    "Twi": "tw", 
    "T\u00fcrkmen": "tk", 
    "T\u00fcrk\u00e7e": "tr", 
    "Vlaams": "nl", 
    "Volap\u00fck": "vo", 
    "Walon": "wa", 
    "Wikang Tagalog": "tl", 
    "Wollof": "wo", 
    "Xitsonga": "ts", 
    "Yor\u00f9b\u00e1": "yo", 
    "af Soomaali": "so", 
    "avesta": "ae", 
    "aymar aru": "ay", 
    "az\u0259rbaycan dili": "az", 
    "bamanankan": "bm", 
    "basa Jawa": "jv", 
    "bosanski jezik": "bs", 
    "brezhoneg": "br", 
    "castellano": "es", 
    "chiChe\u0175a": "ny", 
    "chiShona": "sn", 
    "chinyanja": "ny", 
    "corsu": "co", 
    "dansk": "da", 
    "eesti": "et", 
    "eesti keel": "et", 
    "espa\u00f1ol": "es", 
    "euskara": "eu", 
    "euskera": "eu", 
    "faka Tonga": "to", 
    "fran\u00e7ais": "fr", 
    "f\u00f8royskt": "fo", 
    "gagana fa'a Samoa": "sm", 
    "hrvatski": "hr", 
    "isiNdebele": "nr", 
    "isiXhosa": "xh", 
    "isiZulu": "zu", 
    "kalaallisut": "kl", 
    "kalaallit oqaasii": "kl", 
    "kiRundi": "rn", 
    "langue fran\u00e7aise": "fr", 
    "latine": "la", 
    "latvie\u0161u valoda": "lv", 
    "lietuvi\u0173 kalba": "lt", 
    "lingua corsa": "co", 
    "lingua latina": "la", 
    "polski": "pl", 
    "rom\u00e2n\u0103": "ro", 
    "rumantsch grischun": "rm", 
    "sardu": "sc", 
    "sloven\u010dina": "sk", 
    "sloven\u0161\u010dina": "sl", 
    "suomen kieli": "fi", 
    "suomi": "fi", 
    "svenska": "sv", 
    "te reo M\u0101ori": "mi", 
    "vosa Vakaviti": "fj", 
    "y\u00e2ng\u00e2 t\u00ee s\u00e4ng\u00f6": "sg", 
    "\u00cdslenska": "is", 
    "\u010desky": "cs", 
    "\u010de\u0161tina": "cs", 
    "\u0395\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03ac": "el", 
    "\u0410\u04a7\u0441\u0443\u0430": "ab", 
    "\u0411\u0435\u043b\u0430\u0440\u0443\u0441\u043a\u0430\u044f": "be", 
    "\u0418\u0440\u043e\u043d \u00e6\u0432\u0437\u0430\u0433": "os", 
    "\u041c\u043e\u043d\u0433\u043e\u043b": "mn", 
    "\u0422\u04af\u0440\u043a\u043c\u0435\u043d": "tk", 
    "\u0423\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u0430": "uk", 
    "\u0430\u0432\u0430\u0440 \u043c\u0430\u0446\u04c0": "av", 
    "\u0431\u0430\u0448\u04a1\u043e\u0440\u0442 \u0442\u0435\u043b\u0435": "ba", 
    "\u0431\u044a\u043b\u0433\u0430\u0440\u0441\u043a\u0438 \u0435\u0437\u0438\u043a": "bg", 
    "\u043a\u043e\u043c\u0438 \u043a\u044b\u0432": "kv", 
    "\u043a\u044b\u0440\u0433\u044b\u0437 \u0442\u0438\u043b\u0438": "ky", 
    "\u043c\u0430\u0433\u04c0\u0430\u0440\u0443\u043b \u043c\u0430\u0446\u04c0": "av", 
    "\u043c\u0430\u043a\u0435\u0434\u043e\u043d\u0441\u043a\u0438 \u0458\u0430\u0437\u0438\u043a": "mk", 
    "\u043d\u043e\u0445\u0447\u0438\u0439\u043d \u043c\u043e\u0442\u0442": "ce", 
    "\u0440\u0443\u0441\u0441\u043a\u0438\u0439 \u044f\u0437\u044b\u043a": "ru", 
    "\u0441\u0440\u043f\u0441\u043a\u0438 \u0458\u0435\u0437\u0438\u043a": "sr", 
    "\u0447\u04d1\u0432\u0430\u0448 \u0447\u04d7\u043b\u0445\u0438": "cv", 
    "\u0469\u0437\u044b\u043a\u044a \u0441\u043b\u043e\u0432\u0463\u043d\u044c\u0441\u043a\u044a": "cu", 
    "\u049a\u0430\u0437\u0430\u049b \u0442\u0456\u043b\u0456": "kk", 
    "\u0540\u0561\u0575\u0565\u0580\u0565\u0576": "hy", 
    "\u05d9\u05d9\u05b4\u05d3\u05d9\u05e9": "yi", 
    "\u05e2\u05d1\u05e8\u05d9\u05ea": "he", 
    "\u0627\u0631\u062f\u0648": "ur", 
    "\u0627\u0644\u0639\u0631\u0628\u064a\u0629": "ar", 
    "\u0641\u0627\u0631\u0633\u06cc": "fa", 
    "\u0647\u064e\u0648\u064f\u0633\u064e": "ha", 
    "\u067e\u069a\u062a\u0648": "ps", 
    "\u078b\u07a8\u0788\u07ac\u0780\u07a8": "dv", 
    "\u0928\u0947\u092a\u093e\u0932\u0940": "ne", 
    "\u092a\u093e\u0934\u093f": "pi", 
    "\u092d\u094b\u091c\u092a\u0941\u0930\u0940": "bh", 
    "\u092e\u0930\u093e\u0920\u0940": "mr", 
    "\u0938\u0902\u0938\u094d\u0915\u0943\u0924\u092e\u094d": "sa", 
    "\u0939\u093f\u0902\u0926\u0940": "hi", 
    "\u0939\u093f\u0928\u094d\u0926\u0940": "hi", 
    "\u0985\u09b8\u09ae\u09c0\u09af\u09bc\u09be": "as", 
    "\u09ac\u09be\u0982\u09b2\u09be": "bn", 
    "\u0a97\u0ac1\u0a9c\u0ab0\u0abe\u0aa4\u0ac0": "gu", 
    "\u0b13\u0b21\u0b3c\u0b3f\u0b06": "or", 
    "\u0ba4\u0bae\u0bbf\u0bb4\u0bcd": "ta", 
    "\u0c24\u0c46\u0c32\u0c41\u0c17\u0c41": "te", 
    "\u0c95\u0ca8\u0ccd\u0ca8\u0ca1": "kn", 
    "\u0d2e\u0d32\u0d2f\u0d3e\u0d33\u0d02": "ml", 
    "\u0dc3\u0dd2\u0d82\u0dc4\u0dbd": "si", 
    "\u0e44\u0e17\u0e22": "th", 
    "\u0e9e\u0eb2\u0eaa\u0eb2\u0ea5\u0eb2\u0ea7": "lo", 
    "\u0f56\u0f7c\u0f51\u0f0b\u0f61\u0f72\u0f42": "bo", 
    "\u0f62\u0fab\u0f7c\u0f44\u0f0b\u0f41": "dz", 
    "\u1017\u1019\u102c\u1005\u102c": "my", 
    "\u10e5\u10d0\u10e0\u10d7\u10e3\u10da\u10d8": "ka", 
    "\u1275\u130d\u122d\u129b": "ti", 
    "\u12a0\u121b\u122d\u129b": "am", 
    "\u1403\u14c4\u1483\u144e\u1450\u1466": "iu", 
    "\u140a\u14c2\u1511\u14c8\u142f\u14a7\u140e\u14d0": "oj", 
    "\u14c0\u1426\u1403\u152d\u140d\u140f\u1423": "cr", 
    "\u170f\u1712\u1703\u1705\u1714 \u1706\u1704\u170e\u1713\u1704\u1714": "tl", 
    "\u1797\u17b6\u179f\u17b6\u1781\u17d2\u1798\u17c2\u179a": "km", 
    "\ua187\ua259": "ii"
}
