mapping = [
    {
        "aar": "aa", 
        "abk": "ab", 
        "afr": "af", 
        "aka": "ak", 
        "amh": "am", 
        "ara": "ar", 
        "arg": "an", 
        "asm": "as", 
        "ava": "av", 
        "ave": "ae", 
        "aym": "ay", 
        "aze": "az", 
        "bak": "ba", 
        "bam": "bm", 
        "bel": "be", 
        "ben": "bn", 
        "bih": "bh", 
        "bis": "bi", 
        "bod": "bo", 
        "bos": "bs", 
        "bre": "br", 
        "bul": "bg", 
        "cat": "ca", 
        "ces": "cs", 
        "cha": "ch", 
        "che": "ce", 
        "chu": "cu", 
        "chv": "cv", 
        "cor": "kw", 
        "cos": "co", 
        "cre": "cr", 
        "cym": "cy", 
        "dan": "da", 
        "deu": "de", 
        "div": "dv", 
        "dzo": "dz", 
        "ell": "el", 
        "eng": "en", 
        "epo": "eo", 
        "est": "et", 
        "eus": "eu", 
        "ewe": "ee", 
        "fao": "fo", 
        "fas": "fa", 
        "fij": "fj", 
        "fin": "fi", 
        "fra": "fr", 
        "fry": "fy", 
        "ful": "ff", 
        "gla": "gd", 
        "gle": "ga", 
        "glg": "gl", 
        "glv": "gv", 
        "grn": "gn", 
        "guj": "gu", 
        "hat": "ht", 
        "hau": "ha", 
        "heb": "he", 
        "her": "hz", 
        "hin": "hi", 
        "hmo": "ho", 
        "hrv": "hr", 
        "hun": "hu", 
        "hye": "hy", 
        "ibo": "ig", 
        "ido": "io", 
        "iii": "ii", 
        "iku": "iu", 
        "ile": "ie", 
        "ina": "ia", 
        "ind": "id", 
        "ipk": "ik", 
        "isl": "is", 
        "ita": "it", 
        "jav": "jv", 
        "jpn": "ja", 
        "kal": "kl", 
        "kan": "kn", 
        "kas": "ks", 
        "kat": "ka", 
        "kau": "kr", 
        "kaz": "kk", 
        "khm": "km", 
        "kik": "ki", 
        "kin": "rw", 
        "kir": "ky", 
        "kom": "kv", 
        "kon": "kg", 
        "kor": "ko", 
        "kua": "kj", 
        "kur": "ku", 
        "lao": "lo", 
        "lat": "la", 
        "lav": "lv", 
        "lim": "li", 
        "lin": "ln", 
        "lit": "lt", 
        "ltz": "lb", 
        "lub": "lu", 
        "lug": "lg", 
        "mah": "mh", 
        "mal": "ml", 
        "mar": "mr", 
        "mkd": "mk", 
        "mlg": "mg", 
        "mlt": "mt", 
        "mon": "mn", 
        "mri": "mi", 
        "msa": "ms", 
        "mya": "my", 
        "nau": "na", 
        "nav": "nv", 
        "nbl": "nr", 
        "nde": "nd", 
        "ndo": "ng", 
        "nep": "ne", 
        "nld": "nl", 
        "nno": "nn", 
        "nob": "nb", 
        "nor": "no", 
        "nya": "ny", 
        "oci": "oc", 
        "oji": "oj", 
        "ori": "or", 
        "orm": "om", 
        "oss": "os", 
        "pan": "pa", 
        "pli": "pi", 
        "pol": "pl", 
        "por": "pt", 
        "pus": "ps", 
        "que": "qu", 
        "roh": "rm", 
        "ron": "ro", 
        "run": "rn", 
        "rus": "ru", 
        "sag": "sg", 
        "san": "sa", 
        "sin": "si", 
        "slk": "sk", 
        "slv": "sl", 
        "sme": "se", 
        "smo": "sm", 
        "sna": "sn", 
        "snd": "sd", 
        "som": "so", 
        "sot": "st", 
        "spa": "es", 
        "sqi": "sq", 
        "srd": "sc", 
        "srp": "sr", 
        "ssw": "ss", 
        "sun": "su", 
        "swa": "sw", 
        "swe": "sv", 
        "tah": "ty", 
        "tam": "ta", 
        "tat": "tt", 
        "tel": "te", 
        "tgk": "tg", 
        "tgl": "tl", 
        "tha": "th", 
        "tir": "ti", 
        "ton": "to", 
        "tsn": "tn", 
        "tso": "ts", 
        "tuk": "tk", 
        "tur": "tr", 
        "twi": "tw", 
        "uig": "ug", 
        "ukr": "uk", 
        "urd": "ur", 
        "uzb": "uz", 
        "ven": "ve", 
        "vie": "vi", 
        "vol": "vo", 
        "wln": "wa", 
        "wol": "wo", 
        "xho": "xh", 
        "yid": "yi", 
        "yor": "yo", 
        "zha": "za", 
        "zho": "zh", 
        "zul": "zu"
    }, 
    {
        "alb": "sq", 
        "arm": "hy", 
        "baq": "eu", 
        "bur": "my", 
        "chi": "zh", 
        "cze": "cs", 
        "dut": "nl", 
        "fre": "fr", 
        "geo": "ka", 
        "ger": "de", 
        "gre": "el", 
        "ice": "is", 
        "mac": "mk", 
        "mao": "mi", 
        "may": "ms", 
        "per": "fa", 
        "rum": "ro", 
        "slo": "sk", 
        "tib": "bo", 
        "wel": "cy"
    }, 
    {
        "aar": "aa", 
        "abk": "ab", 
        "afr": "af", 
        "aka": "ak", 
        "amh": "am", 
        "ara": "ar", 
        "arg": "an", 
        "asm": "as", 
        "ava": "av", 
        "ave": "ae", 
        "aym": "ay", 
        "aze": "az", 
        "bak": "ba", 
        "bam": "bm", 
        "bel": "be", 
        "ben": "bn", 
        "bis": "bi", 
        "bod": "bo", 
        "bos": "bs", 
        "bre": "br", 
        "bul": "bg", 
        "cat": "ca", 
        "ces": "cs", 
        "cha": "ch", 
        "che": "ce", 
        "chu": "cu", 
        "chv": "cv", 
        "cor": "kw", 
        "cos": "co", 
        "cre": "cr", 
        "cym": "cy", 
        "dan": "da", 
        "deu": "de", 
        "div": "dv", 
        "dzo": "dz", 
        "ell": "el", 
        "eng": "en", 
        "epo": "eo", 
        "est": "et", 
        "eus": "eu", 
        "ewe": "ee", 
        "fao": "fo", 
        "fas": "fa", 
        "fij": "fj", 
        "fin": "fi", 
        "fra": "fr", 
        "fry": "fy", 
        "ful": "ff", 
        "gla": "gd", 
        "gle": "ga", 
        "glg": "gl", 
        "glv": "gv", 
        "grn": "gn", 
        "guj": "gu", 
        "hat": "ht", 
        "hau": "ha", 
        "heb": "he", 
        "her": "hz", 
        "hin": "hi", 
        "hmo": "ho", 
        "hrv": "hr", 
        "hun": "hu", 
        "hye": "hy", 
        "ibo": "ig", 
        "ido": "io", 
        "iii": "ii", 
        "iku": "iu", 
        "ile": "ie", 
        "ina": "ia", 
        "ind": "id", 
        "ipk": "ik", 
        "isl": "is", 
        "ita": "it", 
        "jav": "jv", 
        "jpn": "ja", 
        "kal": "kl", 
        "kan": "kn", 
        "kas": "ks", 
        "kat": "ka", 
        "kau": "kr", 
        "kaz": "kk", 
        "khm": "km", 
        "kik": "ki", 
        "kin": "rw", 
        "kir": "ky", 
        "kom": "kv", 
        "kon": "kg", 
        "kor": "ko", 
        "kua": "kj", 
        "kur": "ku", 
        "lao": "lo", 
        "lat": "la", 
        "lav": "lv", 
        "lim": "li", 
        "lin": "ln", 
        "lit": "lt", 
        "ltz": "lb", 
        "lub": "lu", 
        "lug": "lg", 
        "mah": "mh", 
        "mal": "ml", 
        "mar": "mr", 
        "mkd": "mk", 
        "mlg": "mg", 
        "mlt": "mt", 
        "mon": "mn", 
        "mri": "mi", 
        "msa": "ms", 
        "mya": "my", 
        "nau": "na", 
        "nav": "nv", 
        "nbl": "nr", 
        "nde": "nd", 
        "ndo": "ng", 
        "nep": "ne", 
        "nld": "nl", 
        "nno": "nn", 
        "nob": "nb", 
        "nor": "no", 
        "nya": "ny", 
        "oci": "oc", 
        "oji": "oj", 
        "ori": "or", 
        "orm": "om", 
        "oss": "os", 
        "pan": "pa", 
        "pli": "pi", 
        "pol": "pl", 
        "por": "pt", 
        "pus": "ps", 
        "que": "qu", 
        "roh": "rm", 
        "ron": "ro", 
        "run": "rn", 
        "rus": "ru", 
        "sag": "sg", 
        "san": "sa", 
        "sin": "si", 
        "slk": "sk", 
        "slv": "sl", 
        "sme": "se", 
        "smo": "sm", 
        "sna": "sn", 
        "snd": "sd", 
        "som": "so", 
        "sot": "st", 
        "spa": "es", 
        "sqi": "sq", 
        "srd": "sc", 
        "srp": "sr", 
        "ssw": "ss", 
        "sun": "su", 
        "swa": "sw", 
        "swe": "sv", 
        "tah": "ty", 
        "tam": "ta", 
        "tat": "tt", 
        "tel": "te", 
        "tgk": "tg", 
        "tgl": "tl", 
        "tha": "th", 
        "tir": "ti", 
        "ton": "to", 
        "tsn": "tn", 
        "tso": "ts", 
        "tuk": "tk", 
        "tur": "tr", 
        "twi": "tw", 
        "uig": "ug", 
        "ukr": "uk", 
        "urd": "ur", 
        "uzb": "uz", 
        "ven": "ve", 
        "vie": "vi", 
        "vol": "vo", 
        "wln": "wa", 
        "wol": "wo", 
        "xho": "xh", 
        "yid": "yi", 
        "yor": "yo", 
        "zha": "za", 
        "zho": "zh", 
        "zul": "zu"
    }, 
    {
        "abkhazian": "ab", 
        "afar": "aa", 
        "afrikaans": "af", 
        "akan": "ak", 
        "albanian": "sq", 
        "amharic": "am", 
        "arabic": "ar", 
        "aragonese": "an", 
        "armenian": "hy", 
        "assamese": "as", 
        "avaric": "av", 
        "avestan": "ae", 
        "aymara": "ay", 
        "azerbaijani": "az", 
        "bambara": "bm", 
        "bashkir": "ba", 
        "basque": "eu", 
        "belarusian": "be", 
        "bengali": "bn", 
        "bihari": "bh", 
        "bislama": "bi", 
        "bosnian": "bs", 
        "breton": "br", 
        "bulgarian": "bg", 
        "burmese": "my", 
        "castilian": "es", 
        "catalan": "ca", 
        "central khmer": "km", 
        "chamorro": "ch", 
        "chechen": "ce", 
        "chewa": "ny", 
        "chichewa": "ny", 
        "chinese": "zh", 
        "chuang": "za", 
        "church slavic": "cu", 
        "church slavonic": "cu", 
        "chuvash": "cv", 
        "cornish": "kw", 
        "corsican": "co", 
        "cree": "cr", 
        "croatian": "hr", 
        "czech": "cs", 
        "danish": "da", 
        "dhivehi": "dv", 
        "divehi": "dv", 
        "dutch": "nl", 
        "dzongkha": "dz", 
        "english": "en", 
        "esperanto": "eo", 
        "estonian": "et", 
        "ewe": "ee", 
        "faroese": "fo", 
        "fijian": "fj", 
        "finnish": "fi", 
        "flemish": "nl", 
        "french": "fr", 
        "fulah": "ff", 
        "gaelic": "gd", 
        "galician": "gl", 
        "ganda": "lg", 
        "georgian": "ka", 
        "german": "de", 
        "gikuyu": "ki", 
        "greenlandic": "kl", 
        "guaran\u00ed": "gn", 
        "gujarati": "gu", 
        "haitian": "ht", 
        "haitian creole": "ht", 
        "hausa": "ha", 
        "herero": "hz", 
        "hindi": "hi", 
        "hiri motu": "ho", 
        "hungarian": "hu", 
        "icelandic": "is", 
        "ido": "io", 
        "igbo": "ig", 
        "indonesian": "id", 
        "interlingua": "ia", 
        "interlingue": "ie", 
        "inuktitut": "iu", 
        "inupiaq": "ik", 
        "irish": "ga", 
        "italian": "it", 
        "japanese": "ja", 
        "javanese": "jv", 
        "kalaallisut": "kl", 
        "kannada": "kn", 
        "kanuri": "kr", 
        "kashmiri": "ks", 
        "kazakh": "kk", 
        "kikuyu": "ki", 
        "kinyarwanda": "rw", 
        "kirghiz": "ky", 
        "komi": "kv", 
        "kongo": "kg", 
        "korean": "ko", 
        "kuanyama": "kj", 
        "kurdish": "ku", 
        "kwanyama": "kj", 
        "kyrgyz": "ky", 
        "lao": "lo", 
        "latin": "la", 
        "latvian": "lv", 
        "letzeburgesch": "lb", 
        "limburgan": "li", 
        "limburger": "li", 
        "limburgish": "li", 
        "lingala": "ln", 
        "lithuanian": "lt", 
        "luba-katanga": "lu", 
        "luxembourgish": "lb", 
        "macedonian": "mk", 
        "malagasy": "mg", 
        "malay": "ms", 
        "malayalam": "ml", 
        "maldivian": "dv", 
        "maltese": "mt", 
        "manx": "gv", 
        "marathi": "mr", 
        "marshallese": "mh", 
        "modern greek": "el", 
        "modern hebrew": "he", 
        "moldavian": "ro", 
        "moldovan": "ro", 
        "mongolian": "mn", 
        "m\u0101ori": "mi", 
        "nauru": "na", 
        "navaho": "nv", 
        "navajo": "nv", 
        "ndonga": "ng", 
        "nepali": "ne", 
        "north ndebele": "nd", 
        "northern sami": "se", 
        "norwegian": "no", 
        "norwegian bokm\u00e5l": "nb", 
        "norwegian nynorsk": "nn", 
        "nuosu": "ii", 
        "nyanja": "ny", 
        "occidental": "ie", 
        "occitan": "oc", 
        "ojibwa": "oj", 
        "old bulgarian": "cu", 
        "old church slavonic": "cu", 
        "old slavonic": "cu", 
        "oriya": "or", 
        "oromo": "om", 
        "ossetian": "os", 
        "ossetic": "os", 
        "panjabi": "pa", 
        "pashto": "ps", 
        "persian": "fa", 
        "polish": "pl", 
        "portuguese": "pt", 
        "punjabi": "pa", 
        "pushto": "ps", 
        "p\u0101li": "pi", 
        "quechua": "qu", 
        "romanian": "ro", 
        "romansh": "rm", 
        "rundi": "rn", 
        "russian": "ru", 
        "samoan": "sm", 
        "sango": "sg", 
        "sanskrit": "sa", 
        "sardinian": "sc", 
        "scottish gaelic": "gd", 
        "serbian": "sr", 
        "shona": "sn", 
        "sichuan yi": "ii", 
        "sindhi": "sd", 
        "sinhala": "si", 
        "sinhalese": "si", 
        "slovak": "sk", 
        "slovene": "sl", 
        "somali": "so", 
        "south ndebele": "nr", 
        "southern sotho": "st", 
        "spanish": "es", 
        "sundanese": "su", 
        "swahili": "sw", 
        "swati": "ss", 
        "swedish": "sv", 
        "tagalog": "tl", 
        "tahitian": "ty", 
        "tajik": "tg", 
        "tamil": "ta", 
        "tatar": "tt", 
        "telugu": "te", 
        "thai": "th", 
        "tibetan": "bo", 
        "tigrinya": "ti", 
        "tonga": "to", 
        "tsonga": "ts", 
        "tswana": "tn", 
        "turkish": "tr", 
        "turkmen": "tk", 
        "twi": "tw", 
        "uighur": "ug", 
        "ukrainian": "uk", 
        "urdu": "ur", 
        "uyghur": "ug", 
        "uzbek": "uz", 
        "valencian": "ca", 
        "venda": "ve", 
        "vietnamese": "vi", 
        "volap\u00fck": "vo", 
        "walloon": "wa", 
        "welsh": "cy", 
        "western frisian": "fy", 
        "wolof": "wo", 
        "xhosa": "xh", 
        "yiddish": "yi", 
        "yoruba": "yo", 
        "zhuang": "za", 
        "zulu": "zu"
    }, 
    {
        "af soomaali": "so", 
        "afaan oromoo": "om", 
        "afaraf": "aa", 
        "afrikaans": "af", 
        "akan": "ak", 
        "aragon\u00e9s": "an", 
        "ava\u00f1e'\u1ebd": "gn", 
        "avesta": "ae", 
        "aymar aru": "ay", 
        "az\u0259rbaycan dili": "az", 
        "bahasa indonesia": "id", 
        "bamanankan": "bm", 
        "basa jawa": "jv", 
        "basa sunda": "su", 
        "bislama": "bi", 
        "bosanski jezik": "bs", 
        "brezhoneg": "br", 
        "castellano": "es", 
        "catal\u00e0": "ca", 
        "chamoru": "ch", 
        "chiche\u0175a": "ny", 
        "chinyanja": "ny", 
        "chishona": "sn", 
        "corsu": "co", 
        "cymraeg": "cy", 
        "dansk": "da", 
        "davvis\u00e1megiella": "se", 
        "deutsch": "de", 
        "din\u00e9 bizaad": "nv", 
        "din\u00e9k\u02bceh\u01f0\u00ed": "nv", 
        "eesti": "et", 
        "eesti keel": "et", 
        "ekakair\u0169 naoero": "na", 
        "english": "en", 
        "espa\u00f1ol": "es", 
        "esperanto": "eo", 
        "euskara": "eu", 
        "euskera": "eu", 
        "e\u028begbe": "ee", 
        "faka tonga": "to", 
        "fran\u00e7ais": "fr", 
        "frysk": "fy", 
        "fulfulde": "ff", 
        "f\u00f8royskt": "fo", 
        "gaeilge": "ga", 
        "gaelg": "gv", 
        "gagana fa'a samoa": "sm", 
        "gailck": "gv", 
        "galego": "gl", 
        "g\u00e0idhlig": "gd", 
        "g\u0129k\u0169y\u0169": "ki", 
        "hausa": "ha", 
        "hiri motu": "ho", 
        "hrvatski": "hr", 
        "ido": "io", 
        "igbo": "ig", 
        "ikinyarwanda": "rw", 
        "interlingua": "ia", 
        "interlingue": "ie", 
        "isindebele": "nr", 
        "isixhosa": "xh", 
        "isizulu": "zu", 
        "italiano": "it", 
        "i\u00f1upiaq": "ik", 
        "i\u00f1upiatun": "ik", 
        "kajin m\u0327aje\u013c": "mh", 
        "kalaallisut": "kl", 
        "kalaallit oqaasii": "kl", 
        "kanuri": "kr", 
        "kernewek": "kw", 
        "kichwa": "qu", 
        "kikongo": "kg", 
        "kirundi": "rn", 
        "kiswahili": "sw", 
        "krey\u00f2l ayisyen": "ht", 
        "kuanyama": "kj", 
        "langue fran\u00e7aise": "fr", 
        "latine": "la", 
        "latvie\u0161u valoda": "lv", 
        "lietuvi\u0173 kalba": "lt", 
        "limburgs": "li", 
        "lingua corsa": "co", 
        "lingua latina": "la", 
        "ling\u00e1la": "ln", 
        "luganda": "lg", 
        "l\u00ebtzebuergesch": "lb", 
        "magyar": "hu", 
        "malagasy fiteny": "mg", 
        "malti": "mt", 
        "nederlands": "nl", 
        "norsk": "no", 
        "norsk bokm\u00e5l": "nb", 
        "norsk nynorsk": "nn", 
        "occitan": "oc", 
        "otjiherero": "hz", 
        "owambo": "ng", 
        "polski": "pl", 
        "portugu\u00eas": "pt", 
        "pulaar": "ff", 
        "pular": "ff", 
        "reo m\u0101`ohi": "ty", 
        "rom\u00e2n\u0103": "ro", 
        "rumantsch grischun": "rm", 
        "runa simi": "qu", 
        "sardu": "sc", 
        "saw cuengh": "za", 
        "sa\u026f cue\u014b\u0185": "za", 
        "sesotho": "st", 
        "setswana": "tn", 
        "shqip": "sq", 
        "siswati": "ss", 
        "sloven\u010dina": "sk", 
        "sloven\u0161\u010dina": "sl", 
        "soomaaliga": "so", 
        "suomen kieli": "fi", 
        "suomi": "fi", 
        "svenska": "sv", 
        "te reo m\u0101ori": "mi", 
        "ti\u1ebfng vi\u1ec7t": "vi", 
        "tshiven\u1e13a": "ve", 
        "twi": "tw", 
        "t\u00fcrkmen": "tk", 
        "t\u00fcrk\u00e7e": "tr", 
        "vlaams": "nl", 
        "volap\u00fck": "vo", 
        "vosa vakaviti": "fj", 
        "walon": "wa", 
        "wikang tagalog": "tl", 
        "wollof": "wo", 
        "xitsonga": "ts", 
        "yor\u00f9b\u00e1": "yo", 
        "y\u00e2ng\u00e2 t\u00ee s\u00e4ng\u00f6": "sg", 
        "\u00edslenska": "is", 
        "\u010desky": "cs", 
        "\u010de\u0161tina": "cs", 
        "\u03b5\u03bb\u03bb\u03b7\u03bd\u03b9\u03ba\u03ac": "el", 
        "\u0430\u0432\u0430\u0440 \u043c\u0430\u0446\u04cf": "av", 
        "\u0430\u04a7\u0441\u0443\u0430": "ab", 
        "\u0431\u0430\u0448\u04a1\u043e\u0440\u0442 \u0442\u0435\u043b\u0435": "ba", 
        "\u0431\u0435\u043b\u0430\u0440\u0443\u0441\u043a\u0430\u044f": "be", 
        "\u0431\u044a\u043b\u0433\u0430\u0440\u0441\u043a\u0438 \u0435\u0437\u0438\u043a": "bg", 
        "\u0438\u0440\u043e\u043d \u00e6\u0432\u0437\u0430\u0433": "os", 
        "\u043a\u043e\u043c\u0438 \u043a\u044b\u0432": "kv", 
        "\u043a\u044b\u0440\u0433\u044b\u0437 \u0442\u0438\u043b\u0438": "ky", 
        "\u043c\u0430\u0433\u04cf\u0430\u0440\u0443\u043b \u043c\u0430\u0446\u04cf": "av", 
        "\u043c\u0430\u043a\u0435\u0434\u043e\u043d\u0441\u043a\u0438 \u0458\u0430\u0437\u0438\u043a": "mk", 
        "\u043c\u043e\u043d\u0433\u043e\u043b": "mn", 
        "\u043d\u043e\u0445\u0447\u0438\u0439\u043d \u043c\u043e\u0442\u0442": "ce", 
        "\u0440\u0443\u0441\u0441\u043a\u0438\u0439 \u044f\u0437\u044b\u043a": "ru", 
        "\u0441\u0440\u043f\u0441\u043a\u0438 \u0458\u0435\u0437\u0438\u043a": "sr", 
        "\u0442\u04af\u0440\u043a\u043c\u0435\u043d": "tk", 
        "\u0443\u043a\u0440\u0430\u0457\u043d\u0441\u044c\u043a\u0430": "uk", 
        "\u0447\u04d1\u0432\u0430\u0448 \u0447\u04d7\u043b\u0445\u0438": "cv", 
        "\u0469\u0437\u044b\u043a\u044a \u0441\u043b\u043e\u0432\u0463\u043d\u044c\u0441\u043a\u044a": "cu", 
        "\u049b\u0430\u0437\u0430\u049b \u0442\u0456\u043b\u0456": "kk", 
        "\u0570\u0561\u0575\u0565\u0580\u0565\u0576": "hy", 
        "\u05d9\u05d9\u05b4\u05d3\u05d9\u05e9": "yi", 
        "\u05e2\u05d1\u05e8\u05d9\u05ea": "he", 
        "\u0627\u0631\u062f\u0648": "ur", 
        "\u0627\u0644\u0639\u0631\u0628\u064a\u0629": "ar", 
        "\u0641\u0627\u0631\u0633\u06cc": "fa", 
        "\u0647\u064e\u0648\u064f\u0633\u064e": "ha", 
        "\u067e\u069a\u062a\u0648": "ps", 
        "\u078b\u07a8\u0788\u07ac\u0780\u07a8": "dv", 
        "\u0928\u0947\u092a\u093e\u0932\u0940": "ne", 
        "\u092a\u093e\u0934\u093f": "pi", 
        "\u092d\u094b\u091c\u092a\u0941\u0930\u0940": "bh", 
        "\u092e\u0930\u093e\u0920\u0940": "mr", 
        "\u0938\u0902\u0938\u094d\u0915\u0943\u0924\u092e\u094d": "sa", 
        "\u0939\u093f\u0902\u0926\u0940": "hi", 
        "\u0939\u093f\u0928\u094d\u0926\u0940": "hi", 
        "\u0985\u09b8\u09ae\u09c0\u09af\u09bc\u09be": "as", 
        "\u09ac\u09be\u0982\u09b2\u09be": "bn", 
        "\u0a97\u0ac1\u0a9c\u0ab0\u0abe\u0aa4\u0ac0": "gu", 
        "\u0b13\u0b21\u0b3c\u0b3f\u0b06": "or", 
        "\u0ba4\u0bae\u0bbf\u0bb4\u0bcd": "ta", 
        "\u0c24\u0c46\u0c32\u0c41\u0c17\u0c41": "te", 
        "\u0c95\u0ca8\u0ccd\u0ca8\u0ca1": "kn", 
        "\u0d2e\u0d32\u0d2f\u0d3e\u0d33\u0d02": "ml", 
        "\u0dc3\u0dd2\u0d82\u0dc4\u0dbd": "si", 
        "\u0e44\u0e17\u0e22": "th", 
        "\u0e9e\u0eb2\u0eaa\u0eb2\u0ea5\u0eb2\u0ea7": "lo", 
        "\u0f56\u0f7c\u0f51\u0f0b\u0f61\u0f72\u0f42": "bo", 
        "\u0f62\u0fab\u0f7c\u0f44\u0f0b\u0f41": "dz", 
        "\u1017\u1019\u102c\u1005\u102c": "my", 
        "\u10e5\u10d0\u10e0\u10d7\u10e3\u10da\u10d8": "ka", 
        "\u1275\u130d\u122d\u129b": "ti", 
        "\u12a0\u121b\u122d\u129b": "am", 
        "\u1403\u14c4\u1483\u144e\u1450\u1466": "iu", 
        "\u140a\u14c2\u1511\u14c8\u142f\u14a7\u140e\u14d0": "oj", 
        "\u14c0\u1426\u1403\u152d\u140d\u140f\u1423": "cr", 
        "\u170f\u1712\u1703\u1705\u1714 \u1706\u1704\u170e\u1713\u1704\u1714": "tl", 
        "\u1797\u17b6\u179f\u17b6\u1781\u17d2\u1798\u17c2\u179a": "km", 
        "\ua187\ua259": "ii"
    }
]
